# Generated by Django 4.2.1 on 2023-06-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_arriendo_id_alter_arriendobicicleta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='deposito_garantia',
            field=models.IntegerField(),
        ),
    ]
